### ISSUE TITLE
Correctly detect libreadline5 on ubuntu

### ISSUE THREAD

**Issue by neggert** [dmwm/cmssh#43]
I'm trying to install cmssh on ubuntu and I'm running into a problem with the detection of the readline library.

```
[~] python cmssh_install.py --help
Traceback (most recent call last):
  File "cmssh_install.py", line 149, in <module>
    DEF_SCRAM_ARCH = get_scram_arch()
  File "cmssh_install.py", line 97, in get_scram_arch
    raise Exception(msg)
Exception: cmssh on Linux requires readline5. Please verify that you have it installed on your system. So far we found
/usr/lib/libreadline.so -> /usr/lib/libreadline.so
```

I do, in fact have libreadline installed, but it's not finding it because it's in a different place.  Here are the contents of the libreadline5 package in ubuntu.

```
[~] dpkg -L libreadline5/.
/etc
/lib
/lib/x86_64-linux-gnu
/lib/x86_64-linux-gnu/libreadline.so.5.2
/lib/x86_64-linux-gnu/libhistory.so.5.2
/usr
/usr/share
/usr/share/doc
/usr/share/doc/libreadline5
/usr/share/doc/libreadline5/USAGE
/usr/share/doc/libreadline5/inputrc.arrows
/usr/share/doc/libreadline5/examples
/usr/share/doc/libreadline5/examples/Inputrc
/usr/share/doc/libreadline5/copyright
/usr/share/doc/libreadline5/changelog.Debian.gz
/usr/share/doc/libreadline5/README.Debian
/lib/x86_64-linux-gnu/libreadline.so.5
/lib/x86_64-linux-gnu/libhistory.so.5
```

If I can make a suggestion, a better way to check for libreadline might be

```
/sbin/ldconfig -p | grep libreadline
```

or the equivalent python command.

**Comment by vkuznet** [comment]
Fixed in #44.
