### ISSUE TITLE
CRAB_2_8_1 is not available.  Update install script to use CRAB_2_8_4.patch1

### ISSUE THREAD

**Issue by adamphunt** [dmwm/cmssh#46]
CRAB_2_8_1 is not available.  Please update installation script to use CRAB_2_8_4_patch1.

Install CRAB
Traceback (most recent call last):
  File "cmssh_install.py", line 1183, in <module>
    main()
  File "cmssh_install.py", line 618, in main
    get_file(url, 'crab.tar.gz', path, debug)
  File "cmssh_install.py", line 357, in get_file
    tar_file.write(getdata(url, debug))
  File "cmssh_install.py", line 335, in getdata
    data = urllib2.urlopen(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 400, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 513, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 432, in error
    result = self._call_chain(_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 372, in _call_chain
    result = func(_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 619, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 400, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 513, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 438, in error
    return self._call_chain(_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 372, in _call_chain
    result = func(_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 521, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden

**Comment by vkuznet** [comment]
Done in 3da0e6f..1d53812 and re-tag in 1.0.0 release.

**Comment by vkuznet** [comment]
Hi Adam,
I fixed CRAB version, committed the fix and re-tag 1.0.0 release. Feel free to download latest code and try it out.
Valentin.
