### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by grasph** [dmwm/cmssh#55]
Hello,

I'd like to install cmssh on my laptop. I'm following the instruction from https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookCmsshTutorial, but I get following error when running the installation program:

$ python cmssh_install.py --install --dir=$PWD
Checking CMSSW
Bootstrap CMSSW
Init CMSSW apt repository
Find latest CMSSW release
Find /bin/sh: 1: source: not found release deps
/bin/sh: 1: source: not found
Traceback (most recent call last):
  File "cmssh_install.py", line 1265, in <module>
    main()
  File "cmssh_install.py", line 595, in main
    name = find_cms_package(apt_init, cmspkg, debug, lookup, rel_pkgs)
  File "cmssh_install.py", line 214, in find_cms_package
    name = natsorted(vers)[-1]
IndexError: list index out of range

Could you help me with this issue?

Philippe.

**Comment by vkuznet** [comment]
Hi Philippe,
It was a while when I made any updates to cmssh, and things progressed in CMS
infrastructure, therefore it is not a surprise to see that installer fails.
But to make any conclusion about the problem I need more information from you.
What is OS are you using? If it is Linux then you had better changes just use
Linux RPMs and use apt-installer, if it is OSX then it depends on its version,
since OSX builds were not made for recent OSX version. Anyway, please add to
the ticket your OS name/version and we can proceed from there.
Thanks,
Valentin.

**Comment by grasph** [comment]
I'm using Debian Wheezy.

Philippe.

On 30/01/15 19:14, Valentin Kuznetsov wrote:

> Hi Philippe,
> It was a while when I made any updates to cmssh, and things progressed 
> in CMS
> infrastructure, therefore it is not a surprise to see that installer 
> fails.
> But to make any conclusion about the problem I need more information 
> from you.
> What is OS are you using? If it is Linux then you had better changes 
> just use
> Linux RPMs and use apt-installer, if it is OSX then it depends on its 
> version,
> since OSX builds were not made for recent OSX version. Anyway, please 
> add to
> the ticket your OS name/version and we can proceed from there.
> Thanks,
> Valentin.
> 
> On 0, grasph notifications@github.com wrote:
> 
> > Hello,
> > 
> > I'd like to install cmssh on my laptop. I'm following the 
> > instruction from 
> > https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookCmsshTutorial, 
> > but I get following error when running the installation program:
> > 
> > $ python cmssh_install.py --install --dir=$PWD
> > Checking CMSSW
> > Bootstrap CMSSW
> > Init CMSSW apt repository
> > Find latest CMSSW release
> > Find /bin/sh: 1: source: not found release deps
> > /bin/sh: 1: source: not found
> > Traceback (most recent call last):
> > File "cmssh_install.py", line 1265, in <module>
> > main()
> > File "cmssh_install.py", line 595, in main
> > name = find_cms_package(apt_init, cmspkg, debug, lookup, rel_pkgs)
> > File "cmssh_install.py", line 214, in find_cms_package
> > name = natsorted(vers)[-1]
> > IndexError: list index out of range
> > 
> > Could you help me with this issue?
> > 
> > Philippe.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/dmwm/cmssh/issues/55
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/dmwm/cmssh/issues/55#issuecomment-72244628.

## 

Philippe GRAS                      CEA Saclay. IRFU/SEDI
Phone: +33 1 69 08 62 81           F-91191 Gif sur Yvette Cedex - FRANCE
Fax:   +33 1 69 08 31 47           Office 141-111
.............................................................................

# CERN Office: 42-1-024              Tel : +41 22 766 2389

**Comment by vkuznet** [comment]
Philippe,
in this case you'll have better changes if you'll just do the following:

export VO_CMS_SW_DIR=$PWD
export LANG="C"
export SCRAM_ARCH=slc6_amd64_gcc481
wget -O $VO_CMS_SW_DIR/bootstrap.sh http://cmsrep.cern.ch/cmssw/cms/bootstrap.sh
sh -x $VO_CMS_SW_DIR/bootstrap.sh setup -path $VO_CMS_SW_DIR -arch $SCRAM_ARCH
source $VO_CMS_SW_DIR/$SCRAM_ARCH/external/apt/*/etc/profile.d/init.sh
apt-get update

followed by normal
apt-cache search <pattern>
apt-get install <package>

For instance, you may install any CMSSW release
apt-cache search cmssw
apt-get install <cmssw release name>

I think you're quite familiar with apt-get/apt-cache because you use Debian.
For more information about this procedure please see:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SDTCMSSW_aptinstaller

Best,
Valentin.

**Comment by grasph** [comment]
Hello Valentin,

I get this error:

/home/pgras/cms/bootstraptmp/BOOTSTRAP/inst/slc6_amd64_gcc481/external/rpm/4.8.0-cms/bin/rpmdb: 
1: 
/home/pgras/cms/bootstraptmp/BOOTSTRAP/inst/slc6_amd64_gcc481/external/rpm/4.8.0-cms/bin/rpmdb: 
cannot create �@@@�@@@@@@@�@@@@�D�DEU@UEU@U@@ 
P�td8C8C@8C@\Q�t/lib64/ld-linux-x86-64.so.2GNUC[W PKJ+MX0E:8)3#C<?ZR@(U/%
                                                                YDB: 
Directory nonexistent
/home/pgras/cms/bootstraptmp/BOOTSTRAP/inst/slc6_amd64_gcc481/external/rpm/4.8.0-cms/bin/rpmdb: 
1: 
/home/pgras/cms/bootstraptmp/BOOTSTRAP/inst/slc6_amd64_gcc481/external/rpm/4.8.0-cms/bin/rpmdb: 
ELF: not found
/home/pgras/cms/bootstraptmp/BOOTSTRAP/inst/slc6_amd64_gcc481/external/rpm/4.8.0-cms/bin/rpmdb: 
5: 
/home/pgras/cms/bootstraptmp/BOOTSTRAP/inst/slc6_amd64_gcc481/external/rpm/4.8.0-cms/bin/rpmdb: 
Syntax error: word unexpected (expecting ")")

My machine is installed in 32bits. Could it be the problem? Do I need it 
to be in 64 bits?

Philippe.

On 01/30/15 20:06, Valentin Kuznetsov wrote:

> export VO_CMS_SW_DIR=$PWD
> export LANG="C"
> export SCRAM_ARCH=slc6_amd64_gcc481
> wget -O $VO_CMS_SW_DIR/bootstrap.sh 
> http://cmsrep.cern.ch/cmssw/cms/bootstrap.sh
> sh -x $VO_CMS_SW_DIR/bootstrap.sh setup -path $VO_CMS_SW_DIR -arch 
> $SCRAM_ARCH

## 

Philippe GRAS                      CEA Saclay. IRFU/SEDI
Phone: +33 1 69 08 62 81           F-91191 Gif sur Yvette Cedex - FRANCE
Fax:   +33 1 69 08 31 47           Office 141-111
.............................................................................

# CERN Office: 42-1-024              Tel : +41 22 766 2389

**Comment by vkuznet** [comment]
Philippe,
yes CMS switched to 64-bit architecture a long time ago, this is visible from
the arch: slc6_amd64_gcc481

It means that the builds we have are for Scientific Linux CERN 6, on AMD-64.
So, you need to have 64-bit architecture to run CMS software.
Valentin.

**Comment by grasph** [comment]
Ok. Thanks Valentin. I will migrate my laptop to 64bit.

Philippe.

On 01/31/15 03:13, Valentin Kuznetsov wrote:

> Philippe,
> yes CMS switched to 64-bit architecture a long time ago, this is 
> visible from
> the arch: slc6_amd64_gcc481
> 
> It means that the builds we have are for Scientific Linux CERN 6, on 
> AMD-64.
> So, you need to have 64-bit architecture to run CMS software.
> Valentin.
> 
> On 0, grasph notifications@github.com wrote:
> 
> > Hello Valentin,
> > 
> > I get this error:
> > 
> > /home/pgras/cms/bootstraptmp/BOOTSTRAP/inst/slc6_amd64_gcc481/external/rpm/4.8.0-cms/bin/rpmdb: 
> > 
> > 1:
> > 
> > /home/pgras/cms/bootstraptmp/BOOTSTRAP/inst/slc6_amd64_gcc481/external/rpm/4.8.0-cms/bin/rpmdb: 
> > 
> > cannot create �@@@�@@@@@@@�@@@@�D�DEU@UEU@U@@
> > P�td8C8C@8C@\Q�t/lib64/ld-linux-x86-64.so.2GNUC[W 
> > PKJ+MX0E:8)3#C<?ZR@(U/%
> > YDB:
> > Directory nonexistent
> > 
> > /home/pgras/cms/bootstraptmp/BOOTSTRAP/inst/slc6_amd64_gcc481/external/rpm/4.8.0-cms/bin/rpmdb: 
> > 
> > 1:
> > 
> > /home/pgras/cms/bootstraptmp/BOOTSTRAP/inst/slc6_amd64_gcc481/external/rpm/4.8.0-cms/bin/rpmdb: 
> > 
> > ELF: not found
> > 
> > /home/pgras/cms/bootstraptmp/BOOTSTRAP/inst/slc6_amd64_gcc481/external/rpm/4.8.0-cms/bin/rpmdb: 
> > 
> > 5:
> > 
> > /home/pgras/cms/bootstraptmp/BOOTSTRAP/inst/slc6_amd64_gcc481/external/rpm/4.8.0-cms/bin/rpmdb: 
> > 
> > Syntax error: word unexpected (expecting ")")
> > 
> > My machine is installed in 32bits. Could it be the problem? Do I 
> > need it
> > to be in 64 bits?
> > 
> > Philippe.
> > 
> > On 01/30/15 20:06, Valentin Kuznetsov wrote:
> > 
> > > export VO_CMS_SW_DIR=$PWD
> > > export LANG="C"
> > > export SCRAM_ARCH=slc6_amd64_gcc481
> > > wget -O $VO_CMS_SW_DIR/bootstrap.sh
> > > http://cmsrep.cern.ch/cmssw/cms/bootstrap.sh
> > > sh -x $VO_CMS_SW_DIR/bootstrap.sh setup -path $VO_CMS_SW_DIR -arch
> > > $SCRAM_ARCH
> > 
> > ## 
> > 
> > Philippe GRAS CEA Saclay. IRFU/SEDI
> > Phone: +33 1 69 08 62 81 F-91191 Gif sur Yvette Cedex - FRANCE
> > Fax: +33 1 69 08 31 47 Office 141-111
> > 
> > .............................................................................
> > CERN Office: 42-1-024 Tel : +41 22 766 2389
> > 
> > # 
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/dmwm/cmssh/issues/55#issuecomment-72293749
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/dmwm/cmssh/issues/55#issuecomment-72299924.

## 

Philippe GRAS                      CEA Saclay. IRFU/SEDI
Phone: +33 1 69 08 62 81           F-91191 Gif sur Yvette Cedex - FRANCE
Fax:   +33 1 69 08 31 47           Office 141-111
.............................................................................

# CERN Office: 42-1-024              Tel : +41 22 766 2389
